find_package(GTest REQUIRED)
include(romea_add_gtest)

romea_add_gtest(test_trilateration_data_buffer test_trilateration_data_buffer.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_rtls_plugin_base test_rtls_plugin_base.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_robot_to_human_rtls_plugin test_robot_to_human_rtls_plugin.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_robot_to_robot_rtls_plugin test_robot_to_robot_rtls_plugin.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_robot_to_world_rtls_plugin test_robot_to_world_rtls_plugin.cpp LIBRARIES ${PROJECT_NAME})
